/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BongaButton {
        /**
          * This attributes determines the background and border color of the button. By default, buttons have a solid background unless the button is inside of a toolbar, in which case it has a transparent background.
         */
        "color"?: 'primary' | 'secondary' | 'tertiary';
        "expand"?: 'block' | 'full';
    }
}
declare global {
    interface HTMLBongaButtonElement extends Components.BongaButton, HTMLStencilElement {
    }
    var HTMLBongaButtonElement: {
        prototype: HTMLBongaButtonElement;
        new (): HTMLBongaButtonElement;
    };
    interface HTMLElementTagNameMap {
        "bonga-button": HTMLBongaButtonElement;
    }
}
declare namespace LocalJSX {
    interface BongaButton {
        /**
          * This attributes determines the background and border color of the button. By default, buttons have a solid background unless the button is inside of a toolbar, in which case it has a transparent background.
         */
        "color"?: 'primary' | 'secondary' | 'tertiary';
        "expand"?: 'block' | 'full';
    }
    interface IntrinsicElements {
        "bonga-button": BongaButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bonga-button": LocalJSX.BongaButton & JSXBase.HTMLAttributes<HTMLBongaButtonElement>;
        }
    }
}
