name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - development
      - main
jobs:
  publish:
    if: github.event.pull_request.merged == true # Condition
    runs-on: ubuntu-latest
